week1/Assignment2: Implemented html code of catty board
pesto-students/vinit-sharma-sairamin pull request #17
Opened 2022-05-05 13:29 UTC by developervinit

Exercise1.2:(2-3hours)- Use "Lato" font for entire text in UI- Use line awesome Icon library for all icons- Cattyboard album image URL:https://vif1g.csb.app/src/assets/cattyboard.jpg- Icons used in assignment:la-barsla-homela-searchla-volume-upla-userla-cogla-spotifyla-soundcloud
la-playla-plusla-ellipsis-hla-step-backwardla-step-forwardla-undo-altla-random- Note: Feel free to use any other font library if you wishGuidelines:1.There should be a separate branch created in GitHub for this exercise.2.The UI should closely match with the screengrab given as sample. This includes thecolors, fonts, icons, text etc.3.Semantic tags should be used for laying out the UI.4.There should be one or more Git commits with meaningful commit messages.

2022-05-05 13:37 UTC, sairamin commented on Week-1/assignment2/index.html
> +    <title>Catty Boeard</title>
Spelling mistake

2022-05-05 13:38 UTC, sairamin commented on Week-1/assignment2/index.html
> +    <div class="super_Container">
superContainer
SuperContainer
super_container

Please use any of the above casing

2022-05-05 13:38 UTC, sairamin commented on Week-1/assignment2/index.html
> +        <div class="cntnt_Container">
content

2022-05-05 13:39 UTC, sairamin commented on Week-1/assignment2/index.html
> +</html>
Add extra line at the end

2022-05-05 13:40 UTC, sairamin commented on Week-1/assignment2/style.css
> +    margin: 42px 0px 42px 0px;
margin: 42px 0px

2022-05-05 13:41 UTC, sairamin commented on Week-1/assignment2/style.css
> +  }
new line

2022-05-06 10:08 UTC, mrkarthik3 requested changes
Please add a screenshot of the project's final look.

2022-05-06 10:08 UTC, mrkarthik3 commented on Week-1/assignment2/index.html
> +    <title>Catty Boeard</title>
@developervinit  Please create a screen shot of the project's final look... add that to project folder.... and push that to GitHub.

Difficult to judge if this code matches with the required look.

2022-05-06 10:08 UTC, mrkarthik3 commented on Week-1/assignment2/index.html
> +                    <tr class="tr">
Please add applicable semantic tags for table... like thead/tbody etc...

2022-05-06 10:08 UTC, mrkarthik3 commented on Week-1/assignment2/style.css
> +    padding: 10px;
Was instructed by our mentor to use multiples of 4 for properties like padding/margin/font-size etc....
That is considered professional.

2022-05-06 10:08 UTC, mrkarthik3 commented on Week-1/assignment2/style.css
> +    margin-left: 35px;
Please apply "multiples of 4" principle here... Make it 36 or 32 px

2022-05-06 10:08 UTC, mrkarthik3 commented on Week-1/assignment2/style.css
> +    margin-top: 126px;
Please apply "multiples of 4" principle here...

2022-05-06 10:08 UTC, mrkarthik3 commented on Week-1/assignment2/style.css
> +    flex-direction: row;
"flex-direction: row" is redundant.... Isn't it ?
Why mention it... It is "row" by default anyway

2022-05-06 10:08 UTC, mrkarthik3 commented on Week-1/assignment2/style.css
> +    margin: 0px 10px 0px 140px;
Please apply "multiples of 4" principle here...

2022-07-17 17:47 UTC, merged